version: '2'
services:
    suiviplanproduction-sonar:
        container_name: suiviplanproduction-sonar
        image: sonarqube:6.2-alpine
        ports:
            - 9000:9000
            - 9092:9092
